/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_builtin/403/': RouteRecordInfo<'/_builtin/403/', '/_builtin/403', Record<never, never>, Record<never, never>>,
    '/_builtin/404/': RouteRecordInfo<'/_builtin/404/', '/_builtin/404', Record<never, never>, Record<never, never>>,
    '/_builtin/500/': RouteRecordInfo<'/_builtin/500/', '/_builtin/500', Record<never, never>, Record<never, never>>,
    '/_builtin/iframe-page/[url]': RouteRecordInfo<'/_builtin/iframe-page/[url]', '/_builtin/iframe-page/:url', { url: ParamValue<true> }, { url: ParamValue<false> }>,
    '/_builtin/login/': RouteRecordInfo<'/_builtin/login/', '/_builtin/login', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
  }
}
