/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/for-details': RouteRecordInfo<'/about/for-details', '/about/for-details', Record<never, never>, Record<never, never>>,
    '/directives/copyDirect/': RouteRecordInfo<'/directives/copyDirect/', '/directives/copyDirect', Record<never, never>, Record<never, never>>,
    '/directives/debounceDirect/': RouteRecordInfo<'/directives/debounceDirect/', '/directives/debounceDirect', Record<never, never>, Record<never, never>>,
    '/directives/dragDirect/': RouteRecordInfo<'/directives/dragDirect/', '/directives/dragDirect', Record<never, never>, Record<never, never>>,
    '/directives/longpressDirect/': RouteRecordInfo<'/directives/longpressDirect/', '/directives/longpressDirect', Record<never, never>, Record<never, never>>,
    '/directives/throttleDirect/': RouteRecordInfo<'/directives/throttleDirect/', '/directives/throttleDirect', Record<never, never>, Record<never, never>>,
    '/directives/watermarkDirect/': RouteRecordInfo<'/directives/watermarkDirect/', '/directives/watermarkDirect', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/link/bing/': RouteRecordInfo<'/link/bing/', '/link/bing', Record<never, never>, Record<never, never>>,
    '/link/docs/': RouteRecordInfo<'/link/docs/', '/link/docs', Record<never, never>, Record<never, never>>,
    '/link/gitee/': RouteRecordInfo<'/link/gitee/', '/link/gitee', Record<never, never>, Record<never, never>>,
    '/link/github/': RouteRecordInfo<'/link/github/', '/link/github', Record<never, never>, Record<never, never>>,
    '/link/juejin/': RouteRecordInfo<'/link/juejin/', '/link/juejin', Record<never, never>, Record<never, never>>,
    '/user-center/': RouteRecordInfo<'/user-center/', '/user-center', Record<never, never>, Record<never, never>>,
  }
}
